# Generated by Django 3.0.7 on 2020-06-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayArchiveView', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
